import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";

import { ConfigProvider } from "../contexts/config-context";

import Footer from "@/components/footer";
import Header from "@/components/header";
import { allura, bebas_neue, noto_sans_jp, zen_old_mincho } from "@/lib/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gtmId = process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID;

  return (
    <html lang="ja" suppressHydrationWarning>
      {gtmId && <GoogleTagManager gtmId={gtmId} />}
      <body
        className={`${noto_sans_jp.variable} ${zen_old_mincho.variable} ${allura.variable} ${bebas_neue.variable} font-noto-sans-jp min-h-dvh antialiased`}
      >
        <ConfigProvider>
          <Header />
          {children}
          <Footer />
        </ConfigProvider>
      </body>
    </html>
  );
}
